### ISSUE TITLE
Error in Pentaho 6.0

### ISSUE THREAD

**Issue by rperez1991** [mysticfall/pivot4j#195] opened 2016-02-16 11:07 UTC
I installed Pivot4j 1.0 from pentaho marketplace, but when i try to create a new Pivot4j Analysis i only get an empty screen. 

¿Do you know how can i fix it?

**Comment by mysticfall** [comment] 2016-02-21 11:45
Hi, 

I suppose there should be more information as to the cause of the problem in the server log. Could you try to reproduce it and see if you can find anything in the log file?

The relevant files are `catalina.out` and `pentaho.log` under the `tomcat/logs` directory, by the way.

Please let me know if you can see anything there.

**Comment by mysticfall** [comment] 2016-05-15 05:51
I've been testing Pivot4J on the latest 6.x version of Pentaho BI but was unable to reproduce the problem.

I'm going to close this issue now, but please feel free to reopen it if you can provide any more information on the issue. Thanks!

**Closed by mysticfall** 2016-05-15 05:51 UTC
Labels: bug, pentaho

**Comment by smartgeosystem** [comment] 2017-02-01 13:17
I have similar problem using Pivor4J with Pentaho CE Server 7 (empty screen after new Pivot4j Analysis).
I have following messages in `catalina.out`:

```
15:43:47,925 ERROR [MDXOlap4jConnection] MDXConnection.ERROR_0002 - Invalid connection properties: driver=mondrian.olap4j.MondrianOlap4jDriver;url=jdbc:mondrian:Catalog=mondrian:/SampleData; DataSource=SampleData; Provider=mondrian; EnableXmla=false; PoolNeeded=false; Locale=ru_RU
mondrian.olap.MondrianException: Mondrian Error:Internal error: Error while creating SQL connection: DataSource=SampleData
	at mondrian.resource.MondrianResource$_Def0.ex(MondrianResource.java:987)
	at mondrian.olap.Util.newInternal(Util.java:2410)
	at mondrian.olap.Util.newError(Util.java:2426)
	at mondrian.rolap.RolapConnection.<init>(RolapConnection.java:247)
	at mondrian.rolap.RolapSchema.<init>(RolapSchema.java:185)
	at mondrian.rolap.RolapSchema.<init>(RolapSchema.java:213)
...

```
and 
```
15:43:47,932 ERROR [Pivot4JExceptionHandler] Обнаружено неизвестное исключение (***Unknown exception**)
javax.faces.FacesException: java.lang.reflect.InvocationTargetException
	at org.apache.myfaces.config.ManagedBeanBuilder.buildManagedBean(ManagedBeanBuilder.java:223)
	at org.apache.myfaces.el.unified.resolver.ManagedBeanResolver.createManagedBean(ManagedBeanResolver.java:333)
	at org.apache.myfaces.el.unified.resolver.ManagedBeanResolver.getValue(ManagedBeanResolver.java:296)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:63)
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179)
	at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:94)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
...
```

Does Pivot4J require mondrian:SampleData to work properly? Should I change something in my configs?

Thanks!

**Comment by smartgeosystem** [comment] 2017-02-01 13:22
I'm new in Pentaho. May be I just don't understand some core concepts...

**Comment by AzarouAmine** [comment] 2019-06-25 10:56
Hello, has this been solved? I'm facing the same problem.

**Comment by mouadyoussef** [comment] 2019-06-26 21:10
Same problem here, any solutions ?
