### ISSUE TITLE
Pivot4J Fails on Drillthrough

### ISSUE THREAD

**Issue by underscores** [mysticfall/pivot4j#207] opened 2017-03-13 09:41 UTC
When I try to drill through certain data sets Pivot4J will cause an IndexOutOfBound exception. It does work with JPivot flawlessly however. It cannot drill through any date if only the time dimension is choosen. Version: 1.0 Development Snapshot, Pentaho Plugin
The problem only occurs when a certain Dimension is not selected. I use a "customer" and a Date Dimension. If I only select the Date Dimension it will not work.  If I add the customer Dimension it will work again.

[catalina_out.txt](https://github.com/mysticfall/pivot4j/files/837759/catalina_out.txt)
[pentaho_log.txt](https://github.com/mysticfall/pivot4j/files/837760/pentaho_log.txt)

**Comment by underscores** [comment] 2017-03-13 13:09
I can also add that I can still drill through certain cells. However the drillthrough will reference the wrong source rows. Actually it will always reference source rows far in the future instead of the proper source for the designated date cell.

**Comment by mysticfall** [comment] 2017-03-18 15:26
Relevant stacktrace: 
```
Caused by: java.lang.IndexOutOfBoundsException: Cell ordinal 95) lies outside CellSet bounds (4, 8)
	at mondrian.olap4j.MondrianOlap4jCellSet.ordinalToCoordinateArray(MondrianOlap4jCellSet.java:155)
	at mondrian.olap4j.MondrianOlap4jCellSet.getCell(MondrianOlap4jCellSet.java:138)
	at org.pivot4j.analytics.ui.ViewHandler$DrillThroughCommandImpl.execute(ViewHandler.java:982)
	at org.pivot4j.analytics.ui.ViewHandler$DrillThroughCommandImpl.execute(ViewHandler.java:966)
	at org.pivot4j.analytics.ui.ViewHandler.executeCommand(ViewHandler.java:640)
	at sun.reflect.GeneratedMethodAccessor1181.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:247)

Caused by: java.lang.IndexOutOfBoundsException: Cell ordinal 68) lies outside CellSet bounds (3, 7)
	at mondrian.olap4j.MondrianOlap4jCellSet.ordinalToCoordinateArray(MondrianOlap4jCellSet.java:155)
	at mondrian.olap4j.MondrianOlap4jCellSet.getCell(MondrianOlap4jCellSet.java:138)
	at org.pivot4j.analytics.ui.ViewHandler$DrillThroughCommandImpl.execute(ViewHandler.java:982)
	at org.pivot4j.analytics.ui.ViewHandler$DrillThroughCommandImpl.execute(ViewHandler.java:966)
	at org.pivot4j.analytics.ui.ViewHandler.executeCommand(ViewHandler.java:640)
	at sun.reflect.GeneratedMethodAccessor1181.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
```
@underscores I tried to reproduce the problem with _SteelWheelsSales_ cube, but was unable to do so.

I used only _Measures_ and _Time_ dimensions on each respective axes like this: 
```sql
SELECT {[Measures].[Quantity]} ON COLUMNS, Hierarchize({[Time].[All Years]}) ON ROWS FROM [SteelWheelsSales]
```
Could you give me some instruction on how to reproduce the problem? Thanks!

**Comment by underscores** [comment] 2017-03-19 18:26
I can give you more information tomorrow. What I can say right now is that the problem appeared after loading a data set that contained a Date far in the future (by 5 months actually). After doing so drill throughs would become extremely slow and end up showing source data far off in the future. Or they would fail with the stacktrace you showed up there. I am not sure if it is somehow related to the date dimension itself. I know I should not load false data like that but it was inevitable as someone tinkered with the source systems. The fact table is also rather sparse. It is based on a transaction grain fact table and sometimes I get information from a source, sometimes I don't. Maybe it is related to those dates who are in the far future? Could that ruin the drill through somehow?

**Comment by underscores** [comment] 2017-03-21 15:43
I cannot give you more input actually. I have the following situation:
Standard Date-Dimension with the Hierachy:
All -> Year -> Month -> Day (Day of Month)
And Dimension tables for the customer, machine, some degenerate dimensions for 2 IDs and that is it
Fact Table: standard fact table with 2 degenerate dimension attributes
Special Data: a few databases have a date in the future (June2017). 
Other Notes: Drill-Through with JPivot works without any problems. Drill-Through will work with Pivot4J once I add another dimension or filter by another hierachy (e.g. customer or machine)

**Comment by underscores** [comment] 2017-03-23 08:38
I hope this might help to track it down. If you want I can also send you my schema file. Although I realize that Mondrian Schemas are not your problem you might find something that could have caused this exclusively with Pivot4J

**Comment by underscores** [comment] 2017-03-23 10:18
I can now give additional input. If I do not use "non empty" it will drill through correctly as well. If I use "Non Empty" it will fail. So this might help to reproduce the bug. Again this is transaction-grain, the fact table is not full for every dimension entry.

**Comment by mysticfall** [comment] 2017-03-23 20:00
Thanks for the information. I cannot begin working on this issue now, but I'll look into it on this weekend. However, please understand that there's chance that I won't be able to fix it.

It's really hard to find the root cause of such a problem without being able to reproduce it on my end. I'll try my best to reproduce the issue based on what you wrote above, and also inspect the relevant code and see if I can guess the cause, in case it doesn't work.

**Comment by underscores** [comment] 2017-03-23 20:05
Thank you, I really appreciate your work. I wish I could give you better input :(

**Comment by mysticfall** [comment] 2017-03-26 03:05
Your mentioning of 'Non Empty' reminds me of this issue(#170), and now I strongly suspect it to be the same problem.

As the root cause hasn't been fixed from the Mondrian's side, I just circumvented the issue by not using cell ordinal in parameters.

Could you test the latest master branch and see if it indeed resolves the issue? If it does, I'll publish it to the marketplace as soon as I fix my CI build, which is currently broken.

**Comment by underscores** [comment] 2017-03-30 09:43
Thank you I will try that out. I have to figure out how to build it though. Did you also check it for the Pentaho Plugin?

**Comment by mysticfall** [comment] 2017-04-02 14:06
Pentaho plugin is just a thin wrapper around the Analytics application, so if it the standalone version works, then probably it'll work on the Pentaho server also.

If you find it difficult to build the source, you can download it from here: 
* https://ci.greencatsoft.com/job/Pivot4J/409/

**Comment by mysticfall** [comment] 2017-05-21 22:34
Ok, I'm closing this and will update the marketplace version today.

**Closed by mysticfall** 2017-05-21 22:34 UTC
